apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-nginx
  name: sample-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-nginx
  type: ClusterIP
status:
  loadBalancer: {}
